site_name: COMP2701
site_url: https://gdoyle87.github.io/COMP2701/
nav:
  - Home: index.md
  - Week 1 - Introduction to C & Data Types: wk_one.md
  - Week 2 - Operators, Math, and Program Flow: wk_two.md
  - Week 3 - Functions, Scope, and Header Files: wk_three.md
  - Week 4 - Enums, Storage Classes, and Memory Layout: wk_four.md
  - Week 5 - Arrays and Strings: wk_five.md
  - Week 6 - Multi-Dimensional Arrays: wk_six.md
  - Midterm Review: midterm.md
  - Week 7 - Dynamic Memory Allocation: wk_seven.md
  - Week 8 - Pointer Introduction: wk_eight.md
  - Week 9 - Pointer Arithmetic and sizeof Operator: wk_nine.md
  - Week 10 - String Functions: wk_ten.md
  - Week 11: wk_eleven.md
  - Final Exam Review: final.md

theme: readthedocs
markdown_extensions:
  - md_in_html

extra_javascript:
  - https://cdn.jsdelivr.net/npm/asciinema-player@3.0.1/dist/bundle/asciinema-player.js

extra_css:
  - https://cdn.jsdelivr.net/npm/asciinema-player@3.0.1/dist/bundle/asciinema-player.css
